services:
- docker
notifications:
  email: false
addons:
  sshknownhosts:
  - 159.65.188.219
env:
  global:
  - REMOTE_USER=deploy
  - REMOTE_HOST=159.65.188.219
  - secure: jj8NmauZigxxEo3IsVIvdFd2bSlWbWXNjyBfwRRnydcfmiIOxg53Nb8buFyf4dNc7FWHngUQgMWJqow3k1o0Q+OJe6AyPUvLX17s2KVnWyEAcBdL8GHsQrBH539UH9hek+yOuNccjlKUv907Ck/yUDWoIBKR4uOezx6qh6XkDfh8+ktgJhtKtnrj00CDFILe7iqczPWhc288h59y+oFEpmjmWj+wHoIezSBNu+yTm2yLYNuSjX5kxrrFcj6WGtu+3n98rqh93Ct8OSnBTItQcTrCbjn9fb+KeuJbEEgQXQOZ+5PlJXjKjyKj3Qpt7y/0xjWjRnfKJuVypgAvAeVebaa2TiwYoBBZmPWzU+uVR2wzO5z8ND8vkvfLS99eSU7gW8HlT3U5isKoH341ET0qIIC6Th/hqADuXOzuRliTid2iT247b9rced/fqdqKsXLAdN520WxXrduX8QbDmKFsyR2UfsNTYFTP6AXTVxs4eBeZhvSFnYELkBEtCrlJWWrNqSw9Ni/Fuobh6K/d85n0Bx2fK4dU5ne4mHyhgKLxBlfdZfVwPb1h6wzgZKgJf9ny9USthW88wMjNmEdkt0IsVKVauvXE1yrizsMT8ItP23ziWKPAgBzfGHKVMRRUvfUkXXFk6BM0VHRCDTDZ21Mt7x3+oVKpPrfXs+9qWGotrXw=
  - secure: FJMxXwvyNFZqL4UQPq73Zd2OpWX1Xzl0bUGZs0Ooisb4FrqlDT44cZHXBsuVX6PBMa8QmqFSVt63B2BkCqKxLoK2KRBG0GKwdVewBQKsMp0jyFvUgdxzzrdy8FsfPPB7u713Rw9i4aowgyuQwYnwoNs78QhQQ9P1sVbToh2wTC85z2e0X6dkRSo3CZfU4dORhnvRC9jZD/gRIO52QIi05bVOxCOOeJkFROEfBP4aA7zHhvSVi0wH71Ong547V1PTvvhmtUEyfX20ig1j7DtSP4ZLZ66K+ssBWuDdTMrvp8ruxRKqHvQiUAEKopTI1UfcyuziDWHWb33ZwAgFmMr9AmHlHmXNMj3dDFsLREb46wVVfFenQU3ycQzxabwIxaoXDNFzw/sDMcz43RER+tC+aolApNBjs8RlCTT6FeZ58ik7RT7aED37lxnw/jJIYzM3Fy/0p2V81FDIQRuigqzwepRHXgx6ByT6OYf0zsODO4M43g/w+JXdr6NX/DJ9xDBwCrvmPoVnpF2Y2rlttj9EemkEro44DIQYlmvkmJOXmSW34T9ACNGPmrOATC2exqJFo306D9+88tPpir7M6qIVeLka4HNRpS40Khdn45vxEQl2IE2Yi1yGipFjWNhhjvr4hWW9sQFYAjOvT6eHT7B3eF+9G+JDZYc94atWwjcfSGg=
before_install:
- openssl aes-256-cbc -k "$super_secret_password" -in super_secret.txt.enc -out super_secret.txt
  -d
- chmod 600 super_secret.txt
- mv super_secret.txt ~/.ssh/id_rsa
- docker build -t jandrey15/nginx:$TRAVIS_BUILD_NUMBER .
- docker build -t jandrey15/nginx:latest .
# - docker run --name my-nginx -d -p 8080:80 jandrey15/nginx:$TRAVIS_BUILD_NUMBER
# - docker ps -a
script:
- echo "Hola mundo"
deploy:
- provider: script
  script: bash scripts/deploy.sh staging
  on:
    branch: stage
- provider: script
  script: bash scripts/deploy.sh production
  on:
    branch: master
