services:
- docker
notifications:
  email: false
addons:
  sshknownhosts:
  - 104.248.3.160
# branches:
#   only:
#   - master
env:
  global:
  # - REMOTEAPPDIR=/var/www/test.com/
  - REMOTEUSER=deploy
  - REMOTEHOST=104.248.3.160
  # - PORT=8080
before_install:
- openssl aes-256-cbc -K $encrypted_b3f7817c4a82_key -iv $encrypted_b3f7817c4a82_iv
  -in deploy.enc -out deploy -d
- chmod 600 deploy_rsa
- mv deploy_rsa ~/.ssh/id_rsa
- docker build -t jandrey15/nginx .
- docker run --name my-nginx -d -p 8080:80 jandrey15/nginx
- docker ps -a
# script:
# - bash _scripts/build.sh
# - bash _scripts/test.sh
deploy:
- provider: script
  script: bash scripts/deploy.sh staging
  on:
    branch: develop
- provider: script
  script: bash scripts/deploy.sh production
  on:
    branch: master
