services:
  - docker

notifications:
  email: false
addons:
  sshknownhosts:
  - 123.45.56.78 # your droplet IP goes here
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/test.com/
  - REMOTEUSER=deploy
  - REMOTEHOST=123.45.56.78 # your droplet IP goes here
  - PORT=8080

before_install:
  - docker build -t jandrey15/nginx .
  - docker run --name my-nginx -d -p 8080:80 jandrey15/nginx
  - docker ps -a

script:
  - bash _scripts/build.sh
  - bash _scripts/test.sh

deploy:
  # deploy develop to the staging environment
  - provider: script
    script: bash scripts/deploy.sh staging
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: bash scripts/deploy.sh production
    on:
      branch: master
